# Generated by Django 5.2.8 on 2025-11-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=100)),
                ('roast_level', models.CharField(choices=[('LIGHT', 'Light Roast'), ('MEDIUM', 'Medium Roast'), ('DARK', 'Dark Roast')], default='MEDIUM', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternationalSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('coffee_bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international_market.coffeebean')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international_market.internationalsupplier')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.AddField(
            model_name='coffeebean',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_beans', to='international_market.internationalsupplier'),
        ),
    ]
